/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'requirement' : IDL.Text,
  'phone' : IDL.Text,
});
export const InquiryRequest = IDL.Record({
  'name' : IDL.Text,
  'requirement' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitInquiry' : IDL.Func([InquiryRequest], [SubmitResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'requirement' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InquiryRequest = IDL.Record({
    'name' : IDL.Text,
    'requirement' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitInquiry' : IDL.Func([InquiryRequest], [SubmitResult], []),
  });
};

export const init = ({ IDL }) => { return []; };